name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore
        run: dotnet restore CheckM8.csproj

      - name: Build
        run: msbuild CheckM8.csproj /p:Configuration=Release /p:Platform="Any CPU" /m /v:minimal

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CheckM8-Release
          path: "bin/Any CPU/Release/net48/"
